version: "3.1"
services:
  db:
    image: postgres:16.2-bookworm
    container_name: poke-guesser-postgres
    restart: unless-stopped
    env_file:
      - ./docker.env
    networks:
      - default
    volumes:
      - ${PWD}/docker-sql-init.sql:/docker-entrypoint-initdb.d/init.sql
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  poke-guesser-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poke-guesser-bot
    restart: unless-stopped
    image: poke-guesser-bot
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./docker.env
    networks:
      - default
volumes:
  database:
networks:
  default:
