version: "3.1"
services:
  db:
    image: postgres:15
    container_name: poke-guesser-postgres
    restart: "no"
    environment:
      # POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - default
    volumes:
      - ${PWD}/docker-sql-init.sql:/docker-entrypoint-initdb.d/init.sql
  poke-guesser-bot:
    build:
      context: ../.
      dockerfile: Dockerfile
    container_name: poke-guesser-bot
    restart: "no"
    image: poke-guesser-bot
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: pokebot
    depends_on:
      - db
    networks:
      - default
volumes:
  database:
networks:
  default:
